"""add user status column, system_setting and rate_limit_rule tables

Revision ID: 02136906e804
Revises: acff9ac8e540
Create Date: 2026-04-12 16:01:55.266514
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '02136906e804'
down_revision: Union[str, None] = 'acff9ac8e540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_setting_category'), 'system_setting', ['category'], unique=False)
    op.create_index(op.f('ix_system_setting_key'), 'system_setting', ['key'], unique=True)
    op.create_index(op.f('ix_system_setting_uuid'), 'system_setting', ['uuid'], unique=True)
    op.create_table('tier',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_projects', sa.Integer(), nullable=False),
    sa.Column('max_docs_per_project', sa.Integer(), nullable=False),
    sa.Column('max_fixes_monthly', sa.Integer(), nullable=False),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=False),
    sa.Column('allowed_models', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('feature_flags', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_tier_deleted_at'), 'tier', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tier_uuid'), 'tier', ['uuid'], unique=True)
    op.create_table('rate_limit_rule',
    sa.Column('tier_id', sa.BigInteger(), nullable=True),
    sa.Column('endpoint_pattern', sa.String(length=200), nullable=False),
    sa.Column('max_requests', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['tier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_id', 'endpoint_pattern', name='uq_rate_limit_tier_endpoint')
    )
    op.create_index(op.f('ix_rate_limit_rule_deleted_at'), 'rate_limit_rule', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_rate_limit_rule_endpoint_pattern'), 'rate_limit_rule', ['endpoint_pattern'], unique=False)
    op.create_index(op.f('ix_rate_limit_rule_tier_id'), 'rate_limit_rule', ['tier_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_rule_uuid'), 'rate_limit_rule', ['uuid'], unique=True)
    op.create_table('usage_tracking',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'metric', 'period_start', name='uq_usage_user_metric_period')
    )
    op.create_index(op.f('ix_usage_tracking_user_id'), 'usage_tracking', ['user_id'], unique=False)
    op.create_index('ix_usage_user_metric_active', 'usage_tracking', ['user_id', 'metric', 'period_end'], unique=False)
    op.add_column('user', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('user', sa.Column('tier_id', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    # Backfill: set status from is_active before dropping the old column
    op.execute("UPDATE \"user\" SET status = CASE WHEN is_active = true THEN 'active' ELSE 'deactivated' END")
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    op.create_index(op.f('ix_user_tier_id'), 'user', ['tier_id'], unique=False)
    op.create_unique_constraint(None, 'user', ['stripe_customer_id'])
    op.create_foreign_key(None, 'user', 'tier', ['tier_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # Backfill: set is_active from status before dropping the status column
    op.execute("UPDATE \"user\" SET is_active = CASE WHEN status = 'active' THEN true ELSE false END")
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_tier_id'), table_name='user')
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_column('user', 'stripe_customer_id')
    op.drop_column('user', 'tier_id')
    op.drop_column('user', 'status')
    op.drop_index('ix_usage_user_metric_active', table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_user_id'), table_name='usage_tracking')
    op.drop_table('usage_tracking')
    op.drop_index(op.f('ix_rate_limit_rule_uuid'), table_name='rate_limit_rule')
    op.drop_index(op.f('ix_rate_limit_rule_tier_id'), table_name='rate_limit_rule')
    op.drop_index(op.f('ix_rate_limit_rule_endpoint_pattern'), table_name='rate_limit_rule')
    op.drop_index(op.f('ix_rate_limit_rule_deleted_at'), table_name='rate_limit_rule')
    op.drop_table('rate_limit_rule')
    op.drop_index(op.f('ix_tier_uuid'), table_name='tier')
    op.drop_index(op.f('ix_tier_deleted_at'), table_name='tier')
    op.drop_table('tier')
    op.drop_index(op.f('ix_system_setting_uuid'), table_name='system_setting')
    op.drop_index(op.f('ix_system_setting_key'), table_name='system_setting')
    op.drop_index(op.f('ix_system_setting_category'), table_name='system_setting')
    op.drop_table('system_setting')
    # ### end Alembic commands ###
